<?php
/**
 * Upment Tracking
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2019 Upment DOO (https://upment.com)
 */
?>
<?php
$_helper = $this->helper('tracking');
$_gtagCode = $this->getGtagCode();
$_bingId = $_helper->getBingId();
$_allowedDomain = $_helper->getAllowedDomain();
if ( ($_allowedDomain == '') || (Mage::getBaseUrl() == 'http://' . $_allowedDomain . '/') || (Mage::getBaseUrl() == 'https://' . $_allowedDomain . '/') ) {
?>
<script>
<?php echo $_gtagCode; ?>
</script>
<?php
if ($_bingId != '') {
  $_bingCode = $this->getBingCode();
?>
<!-- Bing tracker -->
<script>(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"<?php echo $_bingId; ?>"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");</script>
<?php echo $_bingCode; ?>
<!-- / Bing tracker -->
<?php } ?>
<?php } ?>
